<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class Main

    Friend WithEvents FileToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents MenuStrip As System.Windows.Forms.MenuStrip
    Friend WithEvents OptionsToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents StatusStrip As System.Windows.Forms.StatusStrip
    Friend WithEvents Label1 As System.Windows.Forms.Label
    Friend WithEvents InputFolderBrowser As System.Windows.Forms.FolderBrowserDialog
    Friend WithEvents Label2 As System.Windows.Forms.Label
    Friend WithEvents CameraSensitivityScroll As System.Windows.Forms.TrackBar
    Friend WithEvents ToolsToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents OutputFolderBrowser As System.Windows.Forms.FolderBrowserDialog
    Friend WithEvents RAREDecompressorSubDragRWPToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents LoadGraphicsToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents QuitToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents SimpleOpenGlControl1 As Tao.Platform.Windows.SimpleOpenGlControl
    Friend WithEvents TabControl1 As System.Windows.Forms.TabControl
    Friend WithEvents TabPage1 As System.Windows.Forms.TabPage
    Friend WithEvents ModelFolderDialog As System.Windows.Forms.FolderBrowserDialog
    Friend WithEvents ObjectIsolatorToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents FileTreeContextMenu As System.Windows.Forms.ContextMenuStrip
    Friend WithEvents ToolStripMenuItem2 As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents ExportWavefrontModelToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents SaveOBJ As System.Windows.Forms.SaveFileDialog
    Friend WithEvents OpenTexture As System.Windows.Forms.OpenFileDialog
    Friend WithEvents GameToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents BanjoKazooieToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents BanjoTooieToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents GameStatus As System.Windows.Forms.ToolStripStatusLabel
    Friend WithEvents BanjoKazooieToolStripMenuItem1 As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents BanjoTooieToolStripMenuItem1 As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents ResetToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents InvertYAxisToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents CaptureScreenshotToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents SaveScreenPNG As System.Windows.Forms.SaveFileDialog
    Friend WithEvents RenameToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents Button1 As System.Windows.Forms.Button
    Friend WithEvents TextBox1 As System.Windows.Forms.TextBox
    Friend WithEvents Label5 As System.Windows.Forms.Label
    Friend WithEvents TreeView1 As CodersLab.Windows.Controls.TreeView
    Friend WithEvents GroupBox1 As System.Windows.Forms.GroupBox
    Friend WithEvents GroupBox2 As System.Windows.Forms.GroupBox
    Friend WithEvents DonkeyKong64ToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents DonkeyKong64ToolStripMenuItem1 As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents FileTree As CodersLab.Windows.Controls.TreeView
    Friend WithEvents ProgressBar1 As System.Windows.Forms.ProgressBar
    Friend WithEvents ToolStrip As System.Windows.Forms.ToolStrip
    Friend WithEvents Rotate90Left As System.Windows.Forms.ToolStripButton
    Friend WithEvents Rotate90Right As System.Windows.Forms.ToolStripButton
    Friend WithEvents Rotate90Up As System.Windows.Forms.ToolStripButton
    Friend WithEvents Rotate90Down As System.Windows.Forms.ToolStripButton
    Friend WithEvents ToolStripSeparator1 As System.Windows.Forms.ToolStripSeparator
    Friend WithEvents RotateTimer As System.Windows.Forms.Timer
    Friend WithEvents ToggleTextureButton As System.Windows.Forms.ToolStripButton
    Friend WithEvents AxisMarkerToggle As System.Windows.Forms.ToolStripButton
    Friend WithEvents ToolStripSeparator2 As System.Windows.Forms.ToolStripSeparator
    Friend WithEvents ToolStripSeparator3 As System.Windows.Forms.ToolStripSeparator
    Friend WithEvents ToggleWireframeButton As System.Windows.Forms.ToolStripButton
    Friend WithEvents AssociateFilesWithWindowsToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents TabPage2 As System.Windows.Forms.TabPage
    Friend WithEvents Button2 As System.Windows.Forms.Button
    Friend WithEvents Button4 As System.Windows.Forms.Button
    Friend WithEvents Button3 As System.Windows.Forms.Button
    Friend WithEvents ModelContentTree As System.Windows.Forms.TreeView
End Class
